@api = http://localhost:3000/Doctor 

### Pedir Todos los doctores
GET {{api}}

### Crear Nuevo Doctor
POST {{api}}
Content-Type: application/json

{
    "name": "prueba",
    "last_name":"iisi",
    "id_specialty": 1,
    "cel": 11111
}

### Pedir 1
GET {{api}}/5

### Eliminar 1 mediante ID
DELETE {{api}}/4

### Contar Doctores
GET {{api}}/count

### Actualizar Doctores
PUT {{api}}/5
Content-Type: application/json

{
    "name": "JoseLuis",
    "last_name":"Ramirez",
    "id_specialty": 3,
    "cel": 11111
}